name: MLSecOps Week 08

on:
  push:
    branches: [ week_08 ]

jobs:
  mlsecops-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install mlflow scikit-learn pandas numpy matplotlib seaborn -q

      - name: Run Data Poisoning
        run: mkdir -p data && python poison_data.py

      - name: Train & Log to MLflow
        env:
          MLFLOW_TRACKING_URI: ./mlruns
        run: python train_log.py

      - name: Analyze Results
        env:
          MLFLOW_TRACKING_URI: ./mlruns
        run: python analyze.py
